export const DEVELOPMENT_PROFILE = Object.freeze({
  id: "professional-demo",
  name: "Professional Demo — fictional",
  version: 1,
  developmentData: true,
  facts: Object.freeze([
    { key: "fullName", label: "Full name", type: "text", value: "Avery Example", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["full name", "applicant name", "legal name"] },
    { key: "firstName", label: "First name", type: "text", value: "Avery", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["first name", "given name", "firstname"] },
    { key: "lastName", label: "Last name", type: "text", value: "Example", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["last name", "family name", "surname", "lastname"] },
    { key: "username", label: "Preferred username", type: "text", value: "averyx", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["username", "user name", "preferred username", "nickname"] },
    { key: "email", label: "Email", type: "email", value: "avery.example@example.test", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["email", "email address", "applicant email", "contact email"] },
    { key: "personalEmail", label: "Personal email", type: "email", value: "avery.personal@example.test", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["personal email", "private email", "applicant personal email"] },
    { key: "collegeEmail", label: "College email", type: "email", value: "avery.example@northstar.example.test", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["college email", "university email", "student email", "academic email"] },
    { key: "phone", label: "Phone", type: "tel", value: "+1 555 010 2020", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["phone", "phone number", "telephone", "mobile number"] },
    { key: "college", label: "College", type: "text", value: "Northstar Demo University", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["college", "university", "school name", "institution"] },
    { key: "studyYear", label: "Current study year", type: "text", value: "Junior", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["study year", "current year", "current year of study", "class standing"] },
    { key: "currentAddressLine1", label: "Current address line 1", type: "text", value: "120 Example Street", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["current address line 1", "current street"] },
    { key: "currentCity", label: "Current city", type: "text", value: "Sampleton", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["current city"] },
    { key: "currentRegion", label: "Current state", type: "text", value: "CA", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["current state", "current region"] },
    { key: "currentPostalCode", label: "Current postal code", type: "postal_code", value: "90210", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["current postal code", "current zip code"] },
    { key: "permanentAddressLine1", label: "Permanent address line 1", type: "text", value: "8 Fiction Avenue", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["permanent address line 1", "permanent street"] },
    { key: "permanentCity", label: "Permanent city", type: "text", value: "Demo City", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["permanent city"] },
    { key: "permanentRegion", label: "Permanent state", type: "text", value: "NY", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["permanent state", "permanent region"] },
    { key: "degree", label: "Degree", type: "text", value: "BSc Computer Science", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["degree", "degree program"] },
    { key: "graduationYear", label: "Graduation year", type: "year", value: "2027", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["graduation year", "year of graduation"] },
    { key: "projectSnapshotWeb", label: "Campus events planner", type: "project_snapshot", value: "Built a campus events planner with searchable listings and accessible event details.", source: "Fictional development profile · manually approved project snapshot", updatedAt: "2026-09-30", aliases: ["approved project", "project snapshot"] },
    { key: "projectSnapshotData", label: "Transit data explorer", type: "project_snapshot", value: "Created a transit data explorer that summarizes route reliability from a synthetic dataset.", source: "Fictional development profile · manually approved project snapshot", updatedAt: "2026-09-30", aliases: ["approved project", "project snapshot"] },
    { key: "github", label: "GitHub", type: "url", value: "https://github.com/avery-example", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["github", "github profile", "github url"] },
    { key: "portfolio", label: "Portfolio", type: "url", value: "https://avery-example.example.test", source: "Fictional development profile", updatedAt: "2026-09-30", aliases: ["portfolio", "portfolio url", "personal website"] }
  ])
});
